# Memory and build performance
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# Kotlin/Gradle stability (Windows path/caches issues ko avoid)
kotlin.incremental=false
kotlin.daemon.useFallbackStrategy=false

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Allow AGP to work with compileSdk = 35 (if it warns)
android.suppressUnsupportedCompileSdk=35

# Optional: Explicit JDK 17 path (agar java -version 17 na ho)
# org.gradle.java.home=C:\\Program Files\\Java\\jdk-17
